# Import Packages

In [43]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Dense,LSTM,Embedding,Dropout, TimeDistributed
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer
import nltk

# Download the Dataset

In [2]:
filename='wonderland.txt'
with open(filename) as f:
    raw_text=f.read()
raw_text=raw_text.lower()

In [39]:
sen=nltk.tokenize.line_tokenize(raw_text)

In [44]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

# Tokenize

In [3]:
words=nltk.tokenize.word_tokenize(raw_text)

In [4]:
intergetoworddic,wordtointegerdic=dict((i,w) for i,w in enumerate(list(set(words)))),dict((w,i) for i,w in enumerate(list(set(words))))

In [7]:
Total_words=len(words)
unique_word=len(set(words))
print("Total_words:",Total_words)
print("unique_word:",unique_word)

Total_words: 34399
unique_word: 2650


# Encoded the words

In [8]:
Encod=[]
for w in words:
    Encod.append(wordtointegerdic[w])

In [9]:
len(Encod)

34399

# Prepare the dataset into X and Y

In [59]:
def create_X_Y(words):
    X,Y=[],[]
    for i in range(len(words)-6):
        x=np.array(words[i:i+5])
        X.append(np.array(x))
        Y.append(words[i+6])
    return np.asarray(X),np.asarray(Y)

In [60]:
X,Y=create_X_Y(Encod)

In [61]:
X.shape

(34393, 5)

In [62]:
X1=X.reshape(-1,1,5)
X1.shape

(34393, 1, 5)

In [63]:
Y.shape

(34393,)

In [31]:
X1

array([[[2478, 1871, 1935, 1383,  896]],

       [[1871, 1935, 1383,  896, 2478]],

       [[1935, 1383,  896, 2478, 1871]],

       ...,

       [[ 258, 1250, 2539,  832, 1524]],

       [[1250, 2539,  832, 1524,  399]],

       [[2539,  832, 1524,  399, 1597]]])

# Model

In [64]:
model=Sequential()
model.add(LSTM(100, input_shape=(X1.shape[1],X1.shape[2]), return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(100))
model.add(Dropout(0.2))
model.add(Dense(unique_word, activation='softmax'))
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['acc'])


In [65]:
print(model.summary())

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_6 (LSTM)                (None, 1, 100)            42400     
_________________________________________________________________
dropout_6 (Dropout)          (None, 1, 100)            0         
_________________________________________________________________
lstm_7 (LSTM)                (None, 100)               80400     
_________________________________________________________________
dropout_7 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 2650)              267650    
Total params: 390,450
Trainable params: 390,450
Non-trainable params: 0
_________________________________________________________________
None


In [66]:
model.fit(X1,Y,epochs=10)

W0914 20:25:03.633132 15216 deprecation.py:323] From C:\Users\karth\Anaconda3\lib\site-packages\tensorflow\python\ops\math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Epoch 1/10
34393/34393 [==============================] - 13s 366us/sample - loss: 5.8986 - acc: 0.0693
Epoch 2/10
34393/34393 [==============================] - 11s 332us/sample - loss: 5.7006 - acc: 0.0703
Epoch 3/10
34393/34393 [==============================] - 10s 300us/sample - loss: 5.6865 - acc: 0.0703
Epoch 4/10
34393/34393 [==============================] - 10s 295us/sample - loss: 5.6785 - acc: 0.0703
Epoch 5/10
34393/34393 [==============================] - 10s 287us/sample - loss: 5.6661 - acc: 0.0701
Epoch 6/10
34393/34393 [==============================] - 10s 299us/sample - loss: 5.6589 - acc: 0.0703
Epoch 7/10
34393/34393 [==============================] - 12s 351us/sample - loss: 5.6473 - acc: 0.0702
Epoch 8/10
34393/34393 [==============================] - 12s 355us/sample - loss: 5.6376 - acc: 0.0702
Epoch 9/10
34393/34393 [==============================] - 10s 290us/sample - loss: 5.6236 - acc: 0.0700
Epoch 10/10
34393/34393 [==============================] - 10s 2

In [154]:
X1.shape

(2644, 1, 5)

In [155]:
X1[0].shape

(1, 5)

In [160]:
X1[0]

array([[0, 1, 2, 3, 4]])

In [213]:
intergetoworddic[model.predict_classes(X1[200].reshape(1,1,5))[0]]

','

In [177]:
X1[0]

array([[2459, 1599,  191,  148, 1254]])

In [212]:
for i in X1[10]:
    for i1 in i:
        print(intergetoworddic[i1])

lewis
carroll
the
millennium
fulcrum


In [216]:
model.predict_classes(X1)

array([2200, 2200, 2200, ..., 1443, 2200, 2200], dtype=int64)